server:
  port: 8081
spring:
  servlet.multipart:
    max-file-size: 150MB
    max-request-size: 150MB
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5105/ingestion_db
    username: postgres
    password: root
  liquibase.change-log: classpath:db/changelog/db.changelog-master.yaml
