version: '3'
services:
  postgres-court-service:
    image: "ihorbunov/postgres:9"
    ports:
      - 5961:5432
    volumes:
      - courts-db:/var/lib/postgresql
    environment:
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=courts_db'

  postgres-ingestion-service:
    image: "ihorbunov/postgres:9"
    ports:
      - 5105:5432
    volumes:
      - ingestion-db:/var/lib/postgresql
    environment:
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=ingestion_db'
volumes:
  courts-db:
  ingestion-db:
